const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const {chromium}=require('playwright');
const before=fs.readFileSync('dor_trading_v52.html','utf8'),after=fs.readFileSync('index.html','utf8');
const scripts=s=>[...s.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>!m[1].includes('src=')&&!/application\/ld\+json/.test(m[1]));
let checked=0;for(const m of scripts(after)){if(m[2].trim()){new vm.Script(m[2]);checked++;}}
const styles=s=>[...s.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)];
assert.equal(styles(before).length,styles(after).length);
for(const m of styles(after))assert.equal((m[1].match(/{/g)||[]).length,(m[1].match(/}/g)||[]).length);
const declarations=s=>new Set([...s.matchAll(/^(?:async )?(?:function|let|const|var)\s+(\w+)/gm)].map(m=>m[1]));
assert.deepEqual([...declarations(before)].filter(n=>!declarations(after).has(n)),[]);
assert.equal(after,fs.readFileSync('dor_trading_v53.html','utf8'));
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.setDefaultTimeout(5000);
 // Offline fixture: real HTML/CSS/navigation; no authentication, network, user data or financial writes.
 await page.route('**/*',r=>r.abort());
 const clean=s=>s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
 await page.setContent(clean(before));
 const baseline=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);});
 await page.setContent(clean(after));
 await page.addStyleTag({content:'#auth-screen,#welcome-back-screen{display:none!important}'});
 const dup=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);});
 assert.deepEqual(dup.filter(id=>!baseline.includes(id)),[]);
 const main=scripts(after).find(m=>m[2].includes('function sw(name,btn)'))[2];
 function fn(name){const start=main.indexOf('function '+name+'(');assert(start>=0,name);const tail=main.slice(start);const end=tail.indexOf('\n}',tail.indexOf('{'));return tail.slice(0,end+2);}
 const names=['sw','swNav','_updateSidenavActive','_updateNavLabel'];
 let nav=main.slice(main.indexOf('/* v53: one navigation hierarchy'),main.indexOf('function sw(name,btn)'))+'\n'+names.map(fn).join('\n');
 await page.addScriptTag({content:`var currentUser={isAdmin:false};var allow=true;var gateHits=0;var renders=[];var showAdd={};var _NAV_LABELS={};var _sidePanelTabs=[];function canUse(){return allow;}function showUpgradeModal(){gateHits++;}function _hydrateTab(name){const t=document.querySelector('template');}function closeNavMenu(){}function mobNavClose(){}function closeSidePanel(){}function _syncBottomNav(){}function observeCards(){}function closeAddTrade(){document.getElementById('add-trade-modal').classList.remove('open');}\n`+['renderOV','renderFocusPanel','renderBiz','renderStats','renderCal','renderTJ','_coachRenderHome','renderPricing','renderAiAssistant','renderPNL','renderCX','renderAdminPanel','_resizeEcal','renderPersonalGoals','drvLoad','drvRender','_openMerge','_openImport'].map(n=>`function ${n}(){renders.push('${n}');}`).join('\n')+nav+'\n_simpleInit();'});
 assert.equal(await page.locator('#sidenav .sn-item:not(.admin-only)').count(),7);
 assert.equal(await page.locator('#mob-bottom-nav button').count(),5);
 await page.locator('#sni-trades').click();
 assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-trades');
 await page.getByRole('button',{name:'לוח שנה',exact:true}).click();
 assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-calendar');
 assert.equal(await page.locator('#sni-trades').getAttribute('aria-current'),'page');
 await page.getByRole('button',{name:'ייבוא עסקאות',exact:true}).click();
 assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-import');
 await page.locator('#sni-biz').click();await page.getByRole('button',{name:'הוצאות',exact:true}).click();
 await page.locator('#tp-expenses select[aria-label="סוג הוצאה"]').selectOption('custom');
 assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-custom');
 await page.locator('#tp-custom select[aria-label="סוג הוצאה"]').selectOption('expenses');
 assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-expenses');
 await page.locator('#sni-stats').click();
 assert.equal(await page.locator('#simple-stats-details').getAttribute('open'),null);
 await page.locator('#simple-stats-details>summary').click();assert(await page.locator('#simple-stats-details').evaluate(d=>d.open));
 await page.locator('#simple-metrics-toggle').click();assert.equal(await page.locator('#simple-metrics-toggle').getAttribute('aria-expanded'),'true');
 await page.evaluate(()=>allow=false);await page.locator('#sni-trades').click();await page.getByRole('button',{name:'לוח שנה',exact:true}).click();
 assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-trades');assert.equal(await page.evaluate(()=>gateHits),1);
 await page.evaluate(()=>swNav('lr'));assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-overview');
 assert.equal(await page.locator('#tp-overview #focus-goal-gauge-body').count(),1);
 await page.locator('#simple-overview-details>summary').click();
 assert(await page.locator('#ov-row3').isVisible());
 await page.locator('#simple-overview-details>summary').click();
 await page.evaluate(()=>{document.getElementById('add-trade-modal').classList.add('open');document.getElementById('at-sym').value='MES';});
 await page.locator('#trade-extra-details>summary').click();await page.getByRole('button',{name:'פתח מחשבונים',exact:true}).click();
 assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-calc');
 await page.getByRole('button',{name:'חזרה לעסקה',exact:true}).click();
 assert.equal(await page.locator('#at-sym').inputValue(),'MES');
 await page.evaluate(()=>closeAddTrade());await page.locator('#sni-overview').click();
 await page.screenshot({path:'navigation-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await page.addScriptTag({content:"function swMob(name){swNav(name)}"});
 await page.locator('#mbn-ai').click();assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-ai');
 await page.getByRole('button',{name:'אימון ומשמעת',exact:true}).click();assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-coach');
 await page.screenshot({path:'navigation-mobile.png'});
 assert(await page.evaluate(()=>renders.includes('renderBiz')&&renders.includes('_openImport')));
 console.log(JSON.stringify({scriptBlocksChecked:checked,styleBlocks:styles(after).length,newDuplicateIDs:0,removedDeclarations:0,navigation:'desktop and mobile passed',expenseSwitch:'passed',planGate:'passed',lazyImport:'passed',dataWrites:'none (isolated fixture)'}));
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});

