const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const {chromium}=require('playwright');
const html=fs.readFileSync('index.html','utf8'),theme=html.slice(html.indexOf('const THEME_INFO = {'),html.indexOf('// Kept for backward compatibility')),home=html.slice(html.indexOf('/* v54 — compact home.'),html.indexOf('function renderOV() {'));
for(const s of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi))if(!s[1].includes('src=')&&!s[1].includes('ld+json')&&s[2].trim())new vm.Script(s[2]);
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url()==='http://localhost:9555/'?r.fulfill({contentType:'text/html',body:html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'')}):r.abort());await page.goto('http://localhost:9555/');await page.addStyleTag({content:'#auth-screen,#welcome-back-screen{display:none!important}'});
await page.addScriptTag({content:theme});
await page.addScriptTag({content:`var currentUser=null;var selectedAccounts=new Set(['__all__']);var accounts=[{id:'a',name:'חשבון ראשי',goals:{pass:{target:2000}}}];var tradesList=[];function escHtml(s){return String(s).replace(/</g,'&lt;')}function tradeComm(t){return t.fee||0}function tradeNet(t){return t.pnl-tradeComm(t)}function swNav(n){}function openAddTrade(){document.getElementById('add-trade-modal').classList.add('open')}function openAcctGrid(){}function renderAcctMenu(){}function applyAcctFilter(){renderHome()}\n`+home});
await page.evaluate(()=>{tradesList=[{date:_homeDate(new Date()),sym:'NQ',pnl:520,fee:8,acct:'a'}];renderHome()});
for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});for(const mode of ['light','dark']){await page.locator('[data-fayna-mode='+mode+']').click();assert.equal(await page.evaluate(()=>localStorage.getItem('fayna_theme')),mode);const colors=await page.evaluate(()=>({bg:getComputedStyle(document.body).backgroundColor,font:getComputedStyle(document.body).fontFamily,overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(colors.bg,mode==='light'?'rgb(243, 241, 237)':'rgb(17, 19, 21)');assert(colors.font.includes(mode==='light'?'Rubik':'Heebo'));assert(!colors.overflow,'overflow '+width+' '+mode);await page.screenshot({path:'theme-'+mode+'-'+width+'.png',fullPage:true});}}
await page.setViewportSize({width:1440,height:1000});
for(const mode of ['light','dark']){await page.evaluate(mode=>{setFaynaTheme(mode);document.getElementById('add-trade-modal').classList.add('open')},mode);assert.equal(await page.locator('#at-sym').evaluate(e=>getComputedStyle(e).color),mode==='light'?'rgb(41, 44, 53)':'rgb(239, 242, 243)');await page.screenshot({path:'form-'+mode+'.png'});await page.evaluate(()=>document.getElementById('add-trade-modal').classList.remove('open'));}
await page.evaluate(()=>setFaynaTheme('light'));await page.reload();await page.addScriptTag({content:theme});assert.equal(await page.evaluate(()=>document.documentElement.dataset.faynaTheme),'light');
await page.evaluate(()=>{localStorage.setItem('fayna_theme','contrast');_initTheme()});assert.equal(await page.evaluate(()=>document.documentElement.dataset.faynaTheme),'dark');
await page.evaluate(()=>{Object.defineProperty(Storage.prototype,'setItem',{value(){throw Error('blocked')}});setFaynaTheme('light')});assert.equal(await page.evaluate(()=>document.documentElement.dataset.faynaTheme),'light');
assert.deepEqual(errors,[]);console.log('Themes: both palettes/fonts; 1440/390/320 fit; saved preference on reload; old contrast migration; blocked storage; JS syntax passed.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});

