const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),{chromium}=require('playwright');
const html=fs.readFileSync('index.html','utf8');const scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>!m[1].includes('src=')&&!m[1].includes('ld+json'));for(const s of scripts)new vm.Script(s[2]);
const main=scripts.find(m=>m[2].includes('function sw(name,btn)'))[2];
function fn(name){const start=main.indexOf('function '+name+'('),tail=main.slice(start),end=tail.indexOf('\n}',tail.indexOf('{'));assert(start>=0,name);return tail.slice(0,end+2);}
const nav=main.slice(main.indexOf('/* v53: one navigation hierarchy'),main.indexOf('function sw(name,btn)'))+'\n'+['sw','swNav','_updateSidenavActive','_updateNavLabel'].map(fn).join('\n');
const workspace=scripts.find(m=>m[1].includes('workspace-v56-script'))[2],theme=html.slice(html.indexOf('const THEME_INFO'),html.indexOf('// Kept',html.indexOf('const THEME_INFO'))),home=html.slice(html.indexOf('/* v54 — compact home.'),html.indexOf('function renderOV() {'));
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(5000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url()==='http://localhost:9556/'?r.fulfill({contentType:'text/html',body:html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'')}):r.abort());await page.goto('http://localhost:9556/');await page.addStyleTag({content:'#auth-screen,#welcome-back-screen{display:none!important}'});
await page.addScriptTag({content:`var currentUser={isAdmin:true,plan:'pro'}, selectedAccounts=new Set(['__all__']), accounts=[{id:'a',name:'ראשי',status:'funded',withdrawals:[{date:'2026-10-01',amount:700}]}],tradesList=[{date:'2026-10-01',sym:'NQ',pnl:500,acct:'a',btime:'09:30'}],records=[{type:'הוצאה',date:'2026-10-01',amount:2000}],customExpenses=[{date:'2026-10-01',desc:'ציוד',amount:300}],businessEvents=[{id:'i',type:'income',date:'2026-10-01',amount:1000},{id:'e',type:'expense',date:'2026-10-02',amount:100},{id:'p',type:'passed',date:'2026-10-02',amount:null,acctId:'a'}],businessNotes={},commSettings={},customSymbols=[],BIZ_TYPE_INFO={passed:{label:'עבר ללייב'}};var cloudWrites=0;function _cloudSave(){cloudWrites++}function saveBizData(){localStorage.setItem('dor_bizEvents',JSON.stringify(businessEvents));_cloudSave()}function escHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function tradeComm(t){return 0}function tradeNet(t){return t.pnl}function showToast(){}function canUse(){return true}function customConfirm(){return Promise.resolve(true)}function showUpgradeModal(){}function saveAccounts(){}function saveData(){localStorage.setItem("test-trades",JSON.stringify(tradesList))}var showAdd={},_NAV_LABELS={},_sidePanelTabs=[];function mobNavClose(){}function closeNavMenu(){}function closeSidePanel(){}function _syncBottomNav(){}function observeCards(){}function _hydrateTab(name){const t=document.getElementById('tpl-'+name);if(t){document.querySelector('main.main').append(t.content.cloneNode(true));t.remove();if(name==='help')workspaceHelpInit();}}function renderAcctMenu(){}function openAcctGrid(){}function applyAcctFilter(){}function openTradeChart(){}\n`+['renderOV','renderFocusPanel','renderStats','renderCal','renderTJ','_coachRenderHome','renderPricing','renderAiAssistant','renderPNL','renderCX','renderAdminPanel','_resizeEcal','renderPersonalGoals','drvLoad','drvRender','_openMerge','_openImport','renderAll'].map(n=>`function ${n}(){}`).join('\n')+home+theme+nav+workspace+'\n_simpleInit();workspaceInit();renderHome();'});
assert.deepEqual(await page.evaluate(()=>financeTotals(financeRows())),{income:1000,expense:100,net:900});
await page.evaluate(()=>{financeDate=new Date(2026,9,4);financeNavigate();});assert.equal(await page.locator('#finance-workspace .ws-kpis section').count(),3);assert(!(await page.locator('#finance-workspace').textContent()).includes('שריפות'));
const baseline=await page.evaluate(()=>JSON.stringify({accounts,tradesList,records,customExpenses}));
await page.getByRole('button',{name:'הוספת תנועה',exact:true}).click();await page.locator('#finance-modal [name=type]').selectOption('expense');await page.locator('#finance-modal [name=amount]').fill('50');await page.locator('#finance-modal [name=date]').fill('2026-10-04');await page.locator('#finance-modal [name=note]').fill('<img src=x onerror=alert(1)>');await page.locator('#finance-modal button[type=submit]').click();assert.equal(await page.evaluate(()=>financeTotals(financeRows()).net),850);assert.equal(await page.evaluate(()=>JSON.stringify({accounts,tradesList,records,customExpenses})),baseline);assert.equal(await page.locator('#finance-workspace img').count(),0);
await page.evaluate(()=>{selectedAccounts=new Set(['missing']);financeRender()});assert.equal(await page.evaluate(()=>financeTotals(financePeriodRows()).net),850);
await page.locator('#simple-section-nav').getByRole('button',{name:'תנועות',exact:true}).click();await page.getByPlaceholder('תיאור או קטגוריה').fill('img');assert.equal(await page.locator('#finance-rows tbody tr').count(),1);await page.locator('#finance-rows [data-finance-edit]').click();await page.getByRole('button',{name:'העברה לארכיון'}).click();assert.equal(await page.evaluate(()=>financeTotals(financeRows()).net),900);
await page.locator('#simple-section-nav').getByRole('button',{name:'דוחות',exact:true}).click();await page.getByText('רשומות מהמערכת הקודמת',{exact:true}).click();await page.getByRole('button',{name:'הצגת הרשומות',exact:true}).click();assert.equal(await page.locator('#finance-legacy-list tbody tr').count(),5);await page.locator('[data-finance-restore]').click();assert.equal(await page.evaluate(()=>financeTotals(financeRows()).net),850);
await page.evaluate(()=>{businessEvents.find(e=>e.note?.includes('onerror')).note='מנוי תוכנה';});
for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});for(const mode of ['light','dark']){await page.evaluate(mode=>{setFaynaTheme(mode);financeNavigate();},mode);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+width+' '+mode);await page.screenshot({path:'v56-finance-'+mode+'-'+width+'.png',fullPage:true});}}
await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>swNav('trades'));assert.equal(await page.locator('.tp.active').getAttribute('id'),'tp-trades');await page.evaluate(()=>swNav('help'));assert.equal(await page.locator('#tp-help .ws-search').count(),1);
await page.evaluate(()=>swNav('datamgr'));assert.equal(await page.locator('.ws-backups .ws-panel').count(),2);await page.evaluate(()=>swNav('billing'));await page.waitForTimeout(100);assert((await page.locator('#workspace-plan-summary').innerText()).includes('pro'));
assert.equal(await page.evaluate(()=>JSON.stringify({accounts,tradesList,records,customExpenses})),baseline);const restoreCheck=await page.evaluate(async()=>{const tradeBefore=JSON.stringify({accounts,tradesList}), original=JSON.stringify(businessEvents);let exports={};workspaceDownload=(name,text)=>exports[name]=JSON.parse(text);workspaceBackup('finance');workspaceBackup('trading');const file=d=>({files:[{size:100,text:async()=>JSON.stringify(d)}],value:'x'});await workspaceRestore(file({kind:'fayna-finance',version:1,businessEvents:[{id:'new',type:'income',date:'2026-10-04',amount:20},{id:'new',type:'income',date:'2026-10-04',amount:20}]}),'finance');const financeSafe=tradeBefore===JSON.stringify({accounts,tradesList})&&businessEvents.filter(e=>e.id==='new').length===1;const finBefore=JSON.stringify(businessEvents);await workspaceRestore(file({kind:'fayna-trading',version:1,tradesList:[],accounts:[],commSettings:{},customSymbols:[]}),'trading');return {financeSafe,tradingSafe:finBefore===JSON.stringify(businessEvents)&&tradesList.length===0&&localStorage.getItem('test-trades')==='[]',separate:!('tradesList' in exports['finance-backup.json'])&&!('businessEvents' in exports['trading-backup.json'])};});assert.deepEqual(restoreCheck,{financeSafe:true,tradingSafe:true,separate:true});assert.deepEqual(errors,[]);console.log('PASS: independent finance totals, writes do not mutate trading/legacy data, archive/restore, filters, XSS, 3 widths/2 themes, navigation, deferred help, separate backups, billing, syntax');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
